<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6134397780091426"
     crossorigin="anonymous"></script>
    <section class="row">
        <article class="col-md">
            <h3 class="text-dark">Como utilizar o sistema !</h3>
            <iframe width="100%" height="400" src="https://www.youtube.com/embed/ZxJhPx3u9Fw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </article>
        <article class="col-md align-self-center">
            <div class="">
                <a class="btn btn-primary btn-lg btn-block mt-2 p-3" href="/geraRifa">Gerar Rifa</a>
                <a class="btn btn-success btn-lg btn-block mt-2 p-3" href="/realizarSorteio">Realizar Sorteio</a>
                <a class="btn btn-warning btn-lg btn-block mt-2 p-3" href="/verificarResultado">Verificar Resultado</a>
            </div>
        </article>
    </section>
