<html>
<html lang="pt-br">

<head>
	<meta charset="utf-8">
    <meta name="language" content="pt-BR">
    <title>Gera rifa Online</title>
    <meta name="description" content="Gerador de rifa online cartela de rifas online facil e gratuitas com ate 1000 números 200 números ou mais">
    <meta name="robots" content="all">
    <meta name="author" content="James Nepomuceno , @negromuceno">
    <meta name="keywords" content="Gerador rifa , rifa , online ,  cartela rifa , cartela facil, 200 numeros, nomes">

    <meta property="og:type" content="page">
    <meta property="og:url" content="http://gerarifa.online/">
    <meta property="og:title" content="Gera rifa online">
    <meta property="og:image" content="http://gerarifa.online/img/titulosemfundo.png">
    <meta property="og:description" content="Gerador de rifas online personalizado com ate 1000 numeros">

    <meta property="article:author" content="James Nepomuceno">

    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="@gerarifa">
    <meta name="twitter:title" content="Gera rifa online">
    <meta name="twitter:creator" content="@@negromuceno">
    <meta name="twitter:description" content="Gerador de rifas online personalizado com ate 1000 numeros">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

	<link rel="stylesheet" type="text/css" href="css/style.css">
    
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6134397780091426"
     crossorigin="anonymous"></script>

	<script>
		$(document).ready(function() {
			$('#rodape').css("top", $(document).height() - 36);
			$(window).resize(function() {
				$('#rodape').css("top", $(document).height() - 36);
			});
		});
	</script>

</head>

<body>
	<header class="">
		<nav class="navbar navbar-expand-sm navbar-dark bg-dark mb-4" >

			<div class="container">
				<!---LOGO-->
				<a class="navbar-brand" href="/">GeraRifa.online </a>

				<!---Menu Hambuerguer-->
				<button class="navbar-toggler" data-toggle="collapse" data-target="#teste">
					<span class="navbar-toggler-icon"></span>
				</button>

				<!---Nevegaçao-->
				<div class="collapse navbar-collapse" id="teste">
					<ul class="navbar-nav ml-auto">
					<li class="nav-item">
							<a class="nav-link" href="/">Inicio</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="/geraRifa">Gerar Rifa</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="/realizarSorteio">Realizar Sorteio</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="/verificarResultado">Verificar Resultado</a>
						</li>
					</ul>
				</div>
			</div>
			

		</nav>
	</header>
	<div class="container">
		<div >
			<?= $this->content() ?>
		</div>
	</div>
	
	<div class="container">
        	    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6134397780091426"
             crossorigin="anonymous"></script>
        <!-- Index -->
        <ins class="adsbygoogle"
             style="display:block"
             data-ad-client="ca-pub-6134397780091426"
             data-ad-slot="9911078259"
             data-ad-format="auto"
             data-full-width-responsive="true"></ins>
        <script>
             (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
	</div>
	
	<footer id="rodape" class="bg-dark w-100">
		<div class="container p-2">
			<div class="row">
				<div class="col text-center azul">
					© Todos os Diretos Reservados - James Nepomuceno - 2022 <a href="https://negromuceno.com/">@negromuceno</a>
				</div>
			</div>
		</div>
	</footer>

</body>

</html>